/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SchoolSaveVault } from './SchoolSaveVault.js';
export * as factories from './factories/index.js';
export { SchoolSaveVault__factory } from './factories/SchoolSaveVault__factory.js';