/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface SchoolSaveVaultInterface extends Interface {
    getFunction(nameOrSignature: "FEE_BASIS_POINTS" | "contribute" | "createGoal" | "extendDeadline" | "feeCollector" | "getProgress" | "goals" | "increaseTarget" | "nextGoalId" | "release"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ContributionMade" | "DeadlineExtended" | "GoalCreated" | "GoalReleased" | "TargetIncreased"): EventFragment;

    encodeFunctionData(functionFragment: 'FEE_BASIS_POINTS', values?: undefined): string;
encodeFunctionData(functionFragment: 'contribute', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'createGoal', values: [AddressLike, BigNumberish, BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'extendDeadline', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'feeCollector', values?: undefined): string;
encodeFunctionData(functionFragment: 'getProgress', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'goals', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'increaseTarget', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'nextGoalId', values?: undefined): string;
encodeFunctionData(functionFragment: 'release', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'FEE_BASIS_POINTS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'contribute', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createGoal', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'extendDeadline', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'feeCollector', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getProgress', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'goals', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'increaseTarget', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nextGoalId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'release', data: BytesLike): Result;
  }

  
    export namespace ContributionMadeEvent {
      export type InputTuple = [goalId: BigNumberish, contributor: AddressLike, amount: BigNumberish, newSaved: BigNumberish];
      export type OutputTuple = [goalId: bigint, contributor: string, amount: bigint, newSaved: bigint];
      export interface OutputObject {goalId: bigint, contributor: string, amount: bigint, newSaved: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DeadlineExtendedEvent {
      export type InputTuple = [goalId: BigNumberish, newDeadline: BigNumberish];
      export type OutputTuple = [goalId: bigint, newDeadline: bigint];
      export interface OutputObject {goalId: bigint, newDeadline: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace GoalCreatedEvent {
      export type InputTuple = [goalId: BigNumberish, owner: AddressLike, targetAmount: BigNumberish, deadline: BigNumberish, label: string];
      export type OutputTuple = [goalId: bigint, owner: string, targetAmount: bigint, deadline: bigint, label: string];
      export interface OutputObject {goalId: bigint, owner: string, targetAmount: bigint, deadline: bigint, label: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace GoalReleasedEvent {
      export type InputTuple = [goalId: BigNumberish, payoutAddress: AddressLike, amountPaid: BigNumberish, fee: BigNumberish];
      export type OutputTuple = [goalId: bigint, payoutAddress: string, amountPaid: bigint, fee: bigint];
      export interface OutputObject {goalId: bigint, payoutAddress: string, amountPaid: bigint, fee: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TargetIncreasedEvent {
      export type InputTuple = [goalId: BigNumberish, newTargetAmount: BigNumberish];
      export type OutputTuple = [goalId: bigint, newTargetAmount: bigint];
      export interface OutputObject {goalId: bigint, newTargetAmount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface SchoolSaveVault extends BaseContract {
    
    connect(runner?: ContractRunner | null): SchoolSaveVault;
    waitForDeployment(): Promise<this>;

    interface: SchoolSaveVaultInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    FEE_BASIS_POINTS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    contribute: TypedContractMethod<
      [goalId: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    createGoal: TypedContractMethod<
      [payoutAddress: AddressLike, targetAmount: BigNumberish, deadline: BigNumberish, label: string, ],
      [bigint],
      'nonpayable'
    >
    

    
    extendDeadline: TypedContractMethod<
      [goalId: BigNumberish, newDeadline: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    feeCollector: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getProgress: TypedContractMethod<
      [goalId: BigNumberish, ],
      [[bigint, bigint, bigint, bigint] & {saved: bigint, target: bigint, remainingAmount: bigint, secondsRemaining: bigint }],
      'view'
    >
    

    
    goals: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, bigint, bigint, bigint, boolean, string] & {owner: string, payoutAddress: string, targetAmount: bigint, deadline: bigint, saved: bigint, released: boolean, label: string }],
      'view'
    >
    

    
    increaseTarget: TypedContractMethod<
      [goalId: BigNumberish, newTargetAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    nextGoalId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    release: TypedContractMethod<
      [goalId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'FEE_BASIS_POINTS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'contribute'): TypedContractMethod<
      [goalId: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'createGoal'): TypedContractMethod<
      [payoutAddress: AddressLike, targetAmount: BigNumberish, deadline: BigNumberish, label: string, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'extendDeadline'): TypedContractMethod<
      [goalId: BigNumberish, newDeadline: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'feeCollector'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getProgress'): TypedContractMethod<
      [goalId: BigNumberish, ],
      [[bigint, bigint, bigint, bigint] & {saved: bigint, target: bigint, remainingAmount: bigint, secondsRemaining: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'goals'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, bigint, bigint, bigint, boolean, string] & {owner: string, payoutAddress: string, targetAmount: bigint, deadline: bigint, saved: bigint, released: boolean, label: string }],
      'view'
    >;
getFunction(nameOrSignature: 'increaseTarget'): TypedContractMethod<
      [goalId: BigNumberish, newTargetAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'nextGoalId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'release'): TypedContractMethod<
      [goalId: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'ContributionMade'): TypedContractEvent<ContributionMadeEvent.InputTuple, ContributionMadeEvent.OutputTuple, ContributionMadeEvent.OutputObject>;
getEvent(key: 'DeadlineExtended'): TypedContractEvent<DeadlineExtendedEvent.InputTuple, DeadlineExtendedEvent.OutputTuple, DeadlineExtendedEvent.OutputObject>;
getEvent(key: 'GoalCreated'): TypedContractEvent<GoalCreatedEvent.InputTuple, GoalCreatedEvent.OutputTuple, GoalCreatedEvent.OutputObject>;
getEvent(key: 'GoalReleased'): TypedContractEvent<GoalReleasedEvent.InputTuple, GoalReleasedEvent.OutputTuple, GoalReleasedEvent.OutputObject>;
getEvent(key: 'TargetIncreased'): TypedContractEvent<TargetIncreasedEvent.InputTuple, TargetIncreasedEvent.OutputTuple, TargetIncreasedEvent.OutputObject>;

    filters: {
      
      'ContributionMade(uint256,address,uint256,uint256)': TypedContractEvent<ContributionMadeEvent.InputTuple, ContributionMadeEvent.OutputTuple, ContributionMadeEvent.OutputObject>;
      ContributionMade: TypedContractEvent<ContributionMadeEvent.InputTuple, ContributionMadeEvent.OutputTuple, ContributionMadeEvent.OutputObject>;
    

      'DeadlineExtended(uint256,uint256)': TypedContractEvent<DeadlineExtendedEvent.InputTuple, DeadlineExtendedEvent.OutputTuple, DeadlineExtendedEvent.OutputObject>;
      DeadlineExtended: TypedContractEvent<DeadlineExtendedEvent.InputTuple, DeadlineExtendedEvent.OutputTuple, DeadlineExtendedEvent.OutputObject>;
    

      'GoalCreated(uint256,address,uint256,uint256,string)': TypedContractEvent<GoalCreatedEvent.InputTuple, GoalCreatedEvent.OutputTuple, GoalCreatedEvent.OutputObject>;
      GoalCreated: TypedContractEvent<GoalCreatedEvent.InputTuple, GoalCreatedEvent.OutputTuple, GoalCreatedEvent.OutputObject>;
    

      'GoalReleased(uint256,address,uint256,uint256)': TypedContractEvent<GoalReleasedEvent.InputTuple, GoalReleasedEvent.OutputTuple, GoalReleasedEvent.OutputObject>;
      GoalReleased: TypedContractEvent<GoalReleasedEvent.InputTuple, GoalReleasedEvent.OutputTuple, GoalReleasedEvent.OutputObject>;
    

      'TargetIncreased(uint256,uint256)': TypedContractEvent<TargetIncreasedEvent.InputTuple, TargetIncreasedEvent.OutputTuple, TargetIncreasedEvent.OutputObject>;
      TargetIncreased: TypedContractEvent<TargetIncreasedEvent.InputTuple, TargetIncreasedEvent.OutputTuple, TargetIncreasedEvent.OutputObject>;
    
    };
  }