// Single source of truth for talking to the deployed SchoolSaveVault contract.
// Every component that needs to read from or write to the contract imports from here.

// Address of SchoolSaveVault as deployed on BOT Chain testnet.
export const CONTRACT_ADDRESS = "0x80B44cd7069a2E28911073c2faDA7c6aAF71A032";

// Describes the contract's functions and events, generated by Hardhat when the contract compiles.
export const CONTRACT_ABI = [
  {
    "inputs": [
      { "internalType": "address", "name": "_feeCollector", "type": "address" }
    ],
    "stateMutability": "nonpayable",
    "type": "constructor"
  },
  {
    "anonymous": false,
    "inputs": [
      { "indexed": true, "internalType": "uint256", "name": "goalId", "type": "uint256" },
      { "indexed": true, "internalType": "address", "name": "contributor", "type": "address" },
      { "indexed": false, "internalType": "uint256", "name": "amount", "type": "uint256" },
      { "indexed": false, "internalType": "uint256", "name": "newSaved", "type": "uint256" }
    ],
    "name": "ContributionMade",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      { "indexed": true, "internalType": "uint256", "name": "goalId", "type": "uint256" },
      { "indexed": false, "internalType": "uint256", "name": "newDeadline", "type": "uint256" }
    ],
    "name": "DeadlineExtended",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      { "indexed": true, "internalType": "uint256", "name": "goalId", "type": "uint256" },
      { "indexed": true, "internalType": "address", "name": "owner", "type": "address" },
      { "indexed": false, "internalType": "uint256", "name": "targetAmount", "type": "uint256" },
      { "indexed": false, "internalType": "uint256", "name": "deadline", "type": "uint256" },
      { "indexed": false, "internalType": "string", "name": "label", "type": "string" }
    ],
    "name": "GoalCreated",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      { "indexed": true, "internalType": "uint256", "name": "goalId", "type": "uint256" },
      { "indexed": true, "internalType": "address", "name": "payoutAddress", "type": "address" },
      { "indexed": false, "internalType": "uint256", "name": "amountPaid", "type": "uint256" },
      { "indexed": false, "internalType": "uint256", "name": "fee", "type": "uint256" }
    ],
    "name": "GoalReleased",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      { "indexed": true, "internalType": "uint256", "name": "goalId", "type": "uint256" },
      { "indexed": false, "internalType": "uint256", "name": "newTargetAmount", "type": "uint256" }
    ],
    "name": "TargetIncreased",
    "type": "event"
  },
  {
    "inputs": [],
    "name": "FEE_BASIS_POINTS",
    "outputs": [{ "internalType": "uint256", "name": "", "type": "uint256" }],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [{ "internalType": "uint256", "name": "goalId", "type": "uint256" }],
    "name": "contribute",
    "outputs": [],
    "stateMutability": "payable",
    "type": "function"
  },
  {
    "inputs": [
      { "internalType": "address", "name": "payoutAddress", "type": "address" },
      { "internalType": "uint256", "name": "targetAmount", "type": "uint256" },
      { "internalType": "uint256", "name": "deadline", "type": "uint256" },
      { "internalType": "string", "name": "label", "type": "string" }
    ],
    "name": "createGoal",
    "outputs": [{ "internalType": "uint256", "name": "goalId", "type": "uint256" }],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      { "internalType": "uint256", "name": "goalId", "type": "uint256" },
      { "internalType": "uint256", "name": "newDeadline", "type": "uint256" }
    ],
    "name": "extendDeadline",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "feeCollector",
    "outputs": [{ "internalType": "address", "name": "", "type": "address" }],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [{ "internalType": "uint256", "name": "goalId", "type": "uint256" }],
    "name": "getProgress",
    "outputs": [
      { "internalType": "uint256", "name": "saved", "type": "uint256" },
      { "internalType": "uint256", "name": "target", "type": "uint256" },
      { "internalType": "uint256", "name": "remainingAmount", "type": "uint256" },
      { "internalType": "uint256", "name": "secondsRemaining", "type": "uint256" }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [{ "internalType": "uint256", "name": "", "type": "uint256" }],
    "name": "goals",
    "outputs": [
      { "internalType": "address", "name": "owner", "type": "address" },
      { "internalType": "address", "name": "payoutAddress", "type": "address" },
      { "internalType": "uint256", "name": "targetAmount", "type": "uint256" },
      { "internalType": "uint256", "name": "deadline", "type": "uint256" },
      { "internalType": "uint256", "name": "saved", "type": "uint256" },
      { "internalType": "bool", "name": "released", "type": "bool" },
      { "internalType": "string", "name": "label", "type": "string" }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      { "internalType": "uint256", "name": "goalId", "type": "uint256" },
      { "internalType": "uint256", "name": "newTargetAmount", "type": "uint256" }
    ],
    "name": "increaseTarget",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "nextGoalId",
    "outputs": [{ "internalType": "uint256", "name": "", "type": "uint256" }],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [{ "internalType": "uint256", "name": "goalId", "type": "uint256" }],
    "name": "release",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
];